### ISSUE TITLE
pas de récupération 

### ISSUE THREAD

**Issue by valderaplets** [Bastiencc/weather-station-dark-sky#3]
salut, j'ai mis ça dans sensor : 

```
- platform: rest
  resource: https://www.pollens.fr/risks/thea/counties/93
  name: pollens_93
  scan_interval: 14400
  json_attributes:
    - risks
  value_template: '{{ value_json.countyName }}'
```

et j'obtiens ça au rédémarrage :( : 

```
Logger: homeassistant.components.rest.sensor
Source: components/rest/sensor.py:246
Integration: rest (documentation, issues)
First occurred: 13:32:37 (1 occurrences)
Last logged: 13:32:37

REST result could not be parsed as JSON
```

as tu une idée ?

**Comment by Bastiencc** [comment]
ça donne quoi comme resultat un ```curl https://www.pollens.fr/risks/thea/counties/93``` depuis la machine où est installée HA ?

**Comment by gogui63** [comment]
Meme problème chez moi, curl OK : 

`domo@debian:~$ curl https://www.pollens.fr/risks/thea/counties/93
{"countyName":"Seine-Saint-Denis","countyNumber":"93","risks":[{"pollenName":"Tilleul","level":0},{"pollenName":"Ambroisies","level":0},{"pollenName":"Olivier","level":0},{"pollenName":"Plantain","level":0},{"pollenName":"Noisetier","level":0},{"pollenName":"Aulne","level":0},{"pollenName":"Armoise","level":0},{"pollenName":"Ch\u00e2taignier","level":0},{"pollenName":"Urticac\u00e9es","level":0},{"pollenName":"Oseille","level":0},{"pollenName":"Gramin\u00e9es","level":5},{"pollenName":"Ch\u00eane","level":0},{"pollenName":"Platane","level":0},{"pollenName":"Bouleau","level":0},{"pollenName":"Charme","level":0},{"pollenName":"Peuplier","level":0},{"pollenName":"Fr\u00eane","level":0},{"pollenName":"Saule","level":0},{"pollenName":"Cypr\u00e8s","level":0}],"riskLevel":5`

**Comment by valderaplets** [comment]
Curl OK pour moi aussi depuis le web terminal

**Comment by gogui63** [comment]
J'ai commencé à regarder et le retour n'est pas sous json mais text/html

**Comment by valderaplets** [comment]
Arf effectivement ça peut coincer

**Comment by valderaplets** [comment]
il faut peut être manipuler le résultat ?

**Comment by Bastiencc** [comment]
Essayez de forcer le header par exemple https://www.home-assistant.io/integrations/rest/

**Comment by valderaplets** [comment]
> Essayez de forcer le header par exemple https://www.home-assistant.io/integrations/rest/

ça fonctionne !

**Comment by gogui63** [comment]
@valderaplets tu peux me donner le code et quel type d'installation as tu ? Docker / rasperry avec image hassio, ... ?

**Comment by valderaplets** [comment]
```yaml
#pollens
- platform: rest
  resource: https://www.pollens.fr/risks/thea/counties/93
  name: pollens_93
  scan_interval: 14400
  json_attributes:
    - risks
  value_template: '{{ value_json.countyName }}'
  headers:
    User-Agent: Home Assistant
    Content-Type: application/json
```

raspberry avec image hassio
